version: '3.8'

services:
  web:
    build: .
    command: sh -c "python manage.py migrate && gunicorn loan_prediction.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=loanprediction
      - POSTGRES_USER=loanuser
      - POSTGRES_PASSWORD=loanpassword

volumes:
  postgres_data:
  static_volume:
